name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-backend-repo:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/your-backend-repo:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-frontend-repo:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/your-frontend-repo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Deployment steps go here."
          echo "For example, you might SSH into your server and run docker-compose pull and docker-compose up -d."
          # Example: ssh user@your-server.com "cd /path/to/your/app && docker-compose pull && docker-compose up -d"